---
version: "3.9"


# https://github.com/neumayer/mysql-docker-compose-examples/tree/master/innodb-cluster
# https://dev.mysql.com/blog-archive/docker-compose-setup-for-innodb-cluster/
services:
  mysql:
    hostname: mysql_node{{.Task.Slot}}
    image: mysql:latest
    environment:
      REPLICA_ID: "{{.Task.Slot}}"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    networks:
      - mysql
      #- traefik
    ports:
      - mode: host
        published: 3306
        target: 3306
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
        #constraints:
        #- node.labels.mysql==true                # run only on nodes with lable  'mysql'
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.tcp.routers.mysql.entrypoints=mysql"
        - "traefik.tcp.routers.mysql.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.mysql.tls.passthrough=true"
        - "traefik.tcp.services.mysql.loadbalancer.server.port=3306"
        # Dummy config - traefik swarm docs / just to suppress traefik error message 
        - "traefik.http.services.mysql-mysql.loadbalancer.server.port=3306"

volumes:
  mysql_data:
    name: mysql_data_node{{.Task.Slot}}

networks:
  mysql:
    name: mysql
    driver: overlay
    attachable: true
  #traefik:
  #  external: true
