---
version: '3.9'

services:
  shepherd:
    container_name: shepherd
    hostname: shepherd
    image: containrrr/shepherd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - shepherd
    environment:
      SLEEP_TIME: 6h     # https://www.docker.com/increase-rate-limits/
      IGNORELIST_SERVICES: shepherd notify
      #WITH_REGISTRY_AUTH: 'true'
      #WITH_INSECURE_REGISTRY: 'true'
      #WITH_NO_RESOLVE_IMAGE: 'true'
      #FILTER_SERVICES: label=com.mydomain.autodeploy
      APPRISE_SIDECAR_URL: notify:5000
      IMAGE_AUTOCLEAN_LIMIT: 5
      #RUN_ONCE_AND_EXIT: 'true'
      ROLLBACK_ON_FAILURE: 'true'
      UPDATE_OPTIONS: --update-delay=30s
      TZ: Europe/Warsaw
      VERBOSE: 'true'
    deploy:
      placement:
        constraints:
          - node.role == manager

  notify:
    # https://github.com/caronc/apprise?tab=readme-ov-file#productivity-based-notifications
    hostname: notify
    container_name: notify
    image: mazzolino/apprise-microservice:0.1
    environment:
      NOTIFICATION_URLS: ntfy://{token}@{hostname}/{targets}
    networks:
      - shepherd

#volumes:
#  shepherd_data:
#    name: shepherd_data

networks:
  shepherd:
    name: shepherd
    driver: overlay
    attachable: true
