---
version: "3.9"

services:
  qdrant:
    # https://qdrant.tech/documentation/quick-start/
    hostname: qdrant
    container_name: qdrant
    image: qdrant/qdrant:latest
    restart: always
    networks:
      - qdrant
      #- traefik
    ports:
      - 6333:6333   # REST API + Web UI :6333/dashboard
      - 6334:6334   # GRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    ulimits:
      nofile: 10000
    #environment:
      #QDRANT__SERVICE__HOST: "0.0.0.0"
      #QDRANT__SERVICE__READ_ONLY_API_KEY: "your_secret_read_only_api_key_here"
      #QDRANT__SERVICE__API_KEY: "your_secret_api_key_here"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.qdrant.rule=HostSNIRegexp(`^qdrant\\..*`)"
      - "traefik.http.routers.qdrant.service=qdrant-s"
      - "traefik.http.routers.qdrant.entryPoints=web"
      - "traefik.http.services.qdrant-s.loadbalancer.server.port=6333"
      - "traefik.http.services.qdrant-s.loadbalancer.sticky.cookie.name=stickycookie"
      - "traefik.http.services.qdrant-s.loadbalancer.sticky.cookie.secure=true"


volumes:
  qdrant_data:
    name: qdrant_data

networks:
  qdrant:
    name: qdrant
    driver: overlay
    attachable: true
# traefik:
#   external: true