---
version: "3.9"

services:
  baserow:
    # https://baserow.io/docs/installation%2Finstall-with-docker
    # https://baserow.io/docs/installation%2Finstall-with-docker-compose
    hostname: baserow
    container_name: baserow
    image: baserow/baserow:latest
    environment:
      BASEROW_PUBLIC_URL: 'http://localhost'
      WEB_FRONTEND_PORT: ${WEB_FRONTEND_PORT:-80}
      WEB_FRONTEND_SSL_PORT: ${WEB_FRONTEND_SSL_PORT:-443}
      MIGRATE_ON_STARTUP: ${MIGRATE_ON_STARTUP:-True}
      BASEROW_TRIGGER_SYNC_TEMPLATES_AFTER_MIGRATION: ${BASEROW_TRIGGER_SYNC_TEMPLATES_AFTER_MIGRATION:-True}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-baserow}
      SECRET_KEY: ${SECRET_KEY:-baserow}
    ports:
      - mode: host
        published: ${BASEROW_HTTP_PORT:-80}
        target: ${WEB_FRONTEND_PORT:-80}
      - mode: host
        published: ${BASEROW_HTTPS_PORT:-443}
        target: ${WEB_FRONTEND_SSL_PORT:-443}
    networks:
      - baserow
      #- traefik
    ulimits:
      nofile: 10000
    volumes:
      - baserow_data:/baserow/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.baserow.rule=HostRegexp(`^baserow\\..*`)"
      - "traefik.http.routers.baserow.service=baserow-s"
      - "traefik.http.routers.baserow.entryPoints=web"
      - "traefik.http.services.baserow-s.loadbalancer.server.port=${BASEROW_HTTP_PORT:-80}"
      - "traefik.http.services.baserow-s.loadbalancer.sticky.cookie.name=stickycookie"
      - "traefik.http.services.baserow-s.loadbalancer.sticky.cookie.secure=true"

volumes:
  baserow_data:
    name: baserow_data

networks:
  baserow:
    name: baserow
    driver: bridge
    attachable: true
# traefik:
#   external: true
